# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taptapme_rev3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 10, 381, 321))
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../src/images/Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 150, 1121, 421))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SahabatBerhitung = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SahabatBerhitung.setMinimumSize(QtCore.QSize(500, 300))
        self.SahabatBerhitung.setMaximumSize(QtCore.QSize(500, 300))
        self.SahabatBerhitung.setStyleSheet("QPushButton:pressed {\n"
"                background-color: #d0d0d0;\n"
"                border-style: inset;\n"
"   }")
        self.SahabatBerhitung.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Sahabat berhitung.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SahabatBerhitung.setIcon(icon)
        self.SahabatBerhitung.setIconSize(QtCore.QSize(500, 300))
        self.SahabatBerhitung.setCheckable(True)
        self.SahabatBerhitung.setAutoDefault(True)
        self.SahabatBerhitung.setDefault(True)
        self.SahabatBerhitung.setObjectName("SahabatBerhitung")
        self.horizontalLayout_2.addWidget(self.SahabatBerhitung)
        self.SahabatSehat = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SahabatSehat.setMinimumSize(QtCore.QSize(500, 300))
        self.SahabatSehat.setMaximumSize(QtCore.QSize(500, 300))
        self.SahabatSehat.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Sahabat sehat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SahabatSehat.setIcon(icon1)
        self.SahabatSehat.setIconSize(QtCore.QSize(500, 300))
        self.SahabatSehat.setObjectName("SahabatSehat")
        self.horizontalLayout_2.addWidget(self.SahabatSehat)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(930, 530, 241, 102))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CekKamera = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CekKamera.sizePolicy().hasHeightForWidth())
        self.CekKamera.setSizePolicy(sizePolicy)
        self.CekKamera.setMinimumSize(QtCore.QSize(100, 100))
        self.CekKamera.setMaximumSize(QtCore.QSize(100, 100))
        self.CekKamera.setStyleSheet("border-radius:90px")
        self.CekKamera.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Cek kamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CekKamera.setIcon(icon2)
        self.CekKamera.setIconSize(QtCore.QSize(100, 100))
        self.CekKamera.setObjectName("CekKamera")
        self.horizontalLayout.addWidget(self.CekKamera)
        self.Bantuan = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Bantuan.setMinimumSize(QtCore.QSize(100, 100))
        self.Bantuan.setMaximumSize(QtCore.QSize(100, 100))
        self.Bantuan.setStyleSheet("border-radius:90px")
        self.Bantuan.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Bantuan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bantuan.setIcon(icon3)
        self.Bantuan.setIconSize(QtCore.QSize(100, 100))
        self.Bantuan.setObjectName("Bantuan")
        self.horizontalLayout.addWidget(self.Bantuan)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1281, 661))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../src/images/mainMenu/BG - Main menu.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TapTap Me"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
