# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menusahabatsehat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 10, 1071, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(500, 300))
        self.pushButton.setMaximumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Ngurah Sucahya/Downloads/ttd ulum.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.Step1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Step1.setMinimumSize(QtCore.QSize(500, 300))
        self.Step1.setMaximumSize(QtCore.QSize(500, 300))
        self.Step1.setObjectName("Step1")
        self.gridLayout.addWidget(self.Step1, 0, 0, 1, 1)
        self.Step2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Step2.setMinimumSize(QtCore.QSize(500, 300))
        self.Step2.setObjectName("Step2")
        self.gridLayout.addWidget(self.Step2, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(500, 300))
        self.pushButton_2.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.Home_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Home_2.setGeometry(QtCore.QRect(1130, 20, 100, 70))
        self.Home_2.setMinimumSize(QtCore.QSize(100, 70))
        self.Home_2.setMaximumSize(QtCore.QSize(100, 70))
        self.Home_2.setObjectName("Home_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sahabat Sehat"))
        self.pushButton.setText(_translate("MainWindow", "Step 4"))
        self.Step1.setText(_translate("MainWindow", "Step 1"))
        self.Step2.setText(_translate("MainWindow", "Step 2"))
        self.pushButton_2.setText(_translate("MainWindow", "Step 3"))
        self.Home_2.setText(_translate("MainWindow", "Bantuan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
