# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menusahabatberhitung.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 10, 1071, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(500, 300))
        self.pushButton.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Step 4 berhitung.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(500, 300))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.Step1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Step1.setMinimumSize(QtCore.QSize(500, 300))
        self.Step1.setMaximumSize(QtCore.QSize(500, 300))
        self.Step1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Step 1 berhitung.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Step1.setIcon(icon1)
        self.Step1.setIconSize(QtCore.QSize(500, 300))
        self.Step1.setObjectName("Step1")
        self.gridLayout.addWidget(self.Step1, 0, 0, 1, 1)
        self.Step2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Step2.setMinimumSize(QtCore.QSize(500, 300))
        self.Step2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Step 2 berhitung.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Step2.setIcon(icon2)
        self.Step2.setIconSize(QtCore.QSize(500, 300))
        self.Step2.setObjectName("Step2")
        self.gridLayout.addWidget(self.Step2, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(500, 300))
        self.pushButton_2.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Step 3 berhitung.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(500, 300))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.Home_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Home_2.setGeometry(QtCore.QRect(1130, 20, 100, 100))
        self.Home_2.setMinimumSize(QtCore.QSize(100, 100))
        self.Home_2.setMaximumSize(QtCore.QSize(100, 70))
        self.Home_2.setStyleSheet("border-radius:90px")
        self.Home_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../src/images/mainMenu/Button - Bantuan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home_2.setIcon(icon4)
        self.Home_2.setIconSize(QtCore.QSize(100, 100))
        self.Home_2.setObjectName("Home_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1271, 661))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../src/images/mainMenu/BG - Step.png"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.gridLayoutWidget.raise_()
        self.Home_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sahabat Sehat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
