# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taptapme_rev.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 50, 330, 81))
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 160, 1141, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SahabatBerhitung = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SahabatBerhitung.setMinimumSize(QtCore.QSize(500, 200))
        self.SahabatBerhitung.setMaximumSize(QtCore.QSize(500, 200))
        self.SahabatBerhitung.setObjectName("SahabatBerhitung")
        self.horizontalLayout_2.addWidget(self.SahabatBerhitung)
        self.SahabatSehat = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SahabatSehat.setMinimumSize(QtCore.QSize(500, 200))
        self.SahabatSehat.setMaximumSize(QtCore.QSize(500, 200))
        self.SahabatSehat.setObjectName("SahabatSehat")
        self.horizontalLayout_2.addWidget(self.SahabatSehat)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(390, 410, 421, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CekKamera = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CekKamera.sizePolicy().hasHeightForWidth())
        self.CekKamera.setSizePolicy(sizePolicy)
        self.CekKamera.setMinimumSize(QtCore.QSize(300, 60))
        self.CekKamera.setMaximumSize(QtCore.QSize(300, 60))
        self.CekKamera.setObjectName("CekKamera")
        self.horizontalLayout.addWidget(self.CekKamera)
        self.Bantuan = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Bantuan.setMinimumSize(QtCore.QSize(40, 60))
        self.Bantuan.setMaximumSize(QtCore.QSize(100, 60))
        self.Bantuan.setObjectName("Bantuan")
        self.horizontalLayout.addWidget(self.Bantuan)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 630, 134, 16))
        self.label_2.setMaximumSize(QtCore.QSize(400, 20))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TapTap Me"))
        self.label.setText(_translate("MainWindow", "TapTap Me"))
        self.SahabatBerhitung.setText(_translate("MainWindow", "Sahabat Berhitung"))
        self.SahabatSehat.setText(_translate("MainWindow", "Sahabat Sehat"))
        self.CekKamera.setText(_translate("MainWindow", "Cek Kamera"))
        self.Bantuan.setText(_translate("MainWindow", "Bantuan"))
        self.label_2.setText(_translate("MainWindow", "Institut Pertanian Bogor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
