# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taptapme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SahabatBerhitung = QtWidgets.QPushButton(self.centralwidget)
        self.SahabatBerhitung.setMaximumSize(QtCore.QSize(500, 200))
        self.SahabatBerhitung.setObjectName("SahabatBerhitung")
        self.horizontalLayout.addWidget(self.SahabatBerhitung)
        self.SahabatSehat = QtWidgets.QPushButton(self.centralwidget)
        self.SahabatSehat.setMaximumSize(QtCore.QSize(500, 200))
        self.SahabatSehat.setObjectName("SahabatSehat")
        self.horizontalLayout.addWidget(self.SahabatSehat)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.CekKamera = QtWidgets.QPushButton(self.centralwidget)
        self.CekKamera.setMinimumSize(QtCore.QSize(400, 60))
        self.CekKamera.setMaximumSize(QtCore.QSize(400, 60))
        self.CekKamera.setObjectName("CekKamera")
        self.verticalLayout_2.addWidget(self.CekKamera, 0, QtCore.Qt.AlignHCenter)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(100, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(400, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TapTap Me"))
        self.SahabatBerhitung.setText(_translate("MainWindow", "Sahabat Berhitung"))
        self.SahabatSehat.setText(_translate("MainWindow", "Sahabat Sehat"))
        self.CekKamera.setText(_translate("MainWindow", "Cek Kamera"))
        self.label_2.setText(_translate("MainWindow", "Institut Pertanian Bogor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
